/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'answerValue' : string,
  'questionId' : string,
  'imageId' : [] | [string],
  'remarks' : string,
}
export type AppRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'auditor' : null } |
  { 'reviewer' : null };
export interface Client { 'id' : string, 'name' : string, 'enabled' : boolean }
export interface Question {
  'id' : string,
  'clientId' : string,
  'questionLabel' : string,
  'order' : bigint,
  'questionType' : QuestionType,
  'enabled' : boolean,
  'sectionId' : string,
  'isImageMandatory' : boolean,
  'remarksEnabled' : boolean,
  'options' : Array<string>,
}
export type QuestionType = { 'radio' : null } |
  { 'dropdown' : null };
export interface Report {
  'id' : string,
  'status' : ReportStatus,
  'clientId' : string,
  'reviewerAnswers' : Array<Answer>,
  'createdAt' : bigint,
  'auditorAnswers' : Array<Answer>,
  'managerComments' : string,
  'assignedAuditor' : Principal,
  'siteName' : string,
  'updatedAt' : bigint,
  'managerAnswers' : Array<Answer>,
}
export type ReportStatus = { 'submitted' : null } |
  { 'completed' : null } |
  { 'reviewed' : null } |
  { 'draft' : null } |
  { 'pending_re_review' : null };
export interface Section {
  'id' : string,
  'clientId' : string,
  'order' : bigint,
  'name' : string,
  'enabled' : boolean,
}
export type SubmitResult = { 'missingAnswers' : Array<string> } |
  { 'success' : null };
export interface UserProfile { 'name' : string }
export interface UserRecord {
  'principal' : Principal,
  'name' : string,
  'role' : AppRole,
  'enabled' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateClient' : ActorMethod<[[] | [string], string, boolean], string>,
  'addOrUpdateQuestion' : ActorMethod<[Question], string>,
  'addOrUpdateSection' : ActorMethod<
    [[] | [string], string, bigint, string, boolean],
    string
  >,
  'addOrUpdateUser' : ActorMethod<[UserRecord], string>,
  'approveReport' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[string, string], string>,
  'createReport' : ActorMethod<[string, string, Principal], string>,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'disableQuestion' : ActorMethod<[string], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllSections' : ActorMethod<[], Array<Section>>,
  'getCallerAppRole' : ActorMethod<[], AppRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionsByClient' : ActorMethod<[string], Array<Question>>,
  'getQuestionsBySection' : ActorMethod<[string], Array<Question>>,
  'getRegistrationStatus' : ActorMethod<
    [],
    { 'isAuditor' : boolean, 'hasAdmin' : boolean, 'isRegistered' : boolean }
  >,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getSectionsByClient' : ActorMethod<[string], Array<Section>>,
  'getUser' : ActorMethod<[Principal], UserRecord>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'listUsers' : ActorMethod<[], Array<UserRecord>>,
  'saveAuditorAnswers' : ActorMethod<[string, Array<Answer>], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveManagerAnswers' : ActorMethod<[string, Array<Answer>], undefined>,
  'saveReviewerAnswers' : ActorMethod<[string, Array<Answer>], string>,
  'sendBackReport' : ActorMethod<[string, string], string>,
  'submitReport' : ActorMethod<[string], SubmitResult>,
  'submitReview' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];