/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const QuestionType = IDL.Variant({
  'radio' : IDL.Null,
  'dropdown' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'clientId' : IDL.Text,
  'questionLabel' : IDL.Text,
  'order' : IDL.Nat,
  'questionType' : QuestionType,
  'enabled' : IDL.Bool,
  'sectionId' : IDL.Text,
  'isImageMandatory' : IDL.Bool,
  'remarksEnabled' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const AppRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'auditor' : IDL.Null,
  'reviewer' : IDL.Null,
});
export const UserRecord = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : AppRole,
  'enabled' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Section = IDL.Record({
  'id' : IDL.Text,
  'clientId' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const AppUserPublic = IDL.Record({
  'username' : IDL.Text,
  'originalRole' : AppRole,
  'elevatedUntil' : IDL.Opt(IDL.Int),
  'role' : AppRole,
  'fullName' : IDL.Text,
  'isEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ReportStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'completed' : IDL.Null,
  'reviewed' : IDL.Null,
  'draft' : IDL.Null,
  'pending_re_review' : IDL.Null,
});
export const Answer = IDL.Record({
  'answerValue' : IDL.Text,
  'questionId' : IDL.Text,
  'imageId' : IDL.Opt(IDL.Text),
  'remarks' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'status' : ReportStatus,
  'clientId' : IDL.Text,
  'reviewerAnswers' : IDL.Vec(Answer),
  'createdAt' : IDL.Int,
  'auditorAnswers' : IDL.Vec(Answer),
  'managerComments' : IDL.Text,
  'assignedAuditor' : IDL.Principal,
  'siteName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'managerAnswers' : IDL.Vec(Answer),
});
export const AuditBlob = IDL.Record({
  'status' : IDL.Text,
  'lastSavedAt' : IDL.Int,
  'dataJson' : IDL.Text,
  'siteId' : IDL.Text,
});
export const Client = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const TemplateBlob = IDL.Record({
  'id' : IDL.Text,
  'createdBy' : IDL.Text,
  'updatedAt' : IDL.Int,
  'dataJson' : IDL.Text,
});
export const AppUser = IDL.Record({
  'username' : IDL.Text,
  'originalRole' : AppRole,
  'elevatedUntil' : IDL.Opt(IDL.Int),
  'role' : AppRole,
  'fullName' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'passwordHash' : IDL.Text,
});
export const SubmitResult = IDL.Variant({
  'missingAnswers' : IDL.Vec(IDL.Text),
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateClient' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'addOrUpdateQuestion' : IDL.Func([Question], [IDL.Text], []),
  'addOrUpdateSection' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'addOrUpdateUser' : IDL.Func([UserRecord], [IDL.Text], []),
  'appUserHasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'approveReport' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal],
      [IDL.Text],
      [],
    ),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'deleteTemplateBlob' : IDL.Func([IDL.Text], [], []),
  'disableQuestion' : IDL.Func([IDL.Text], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getAppUserPublic' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AppUserPublic)],
      ['query'],
    ),
  'getCallerAppRole' : IDL.Func([], [AppRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestionsByClient' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getQuestionsBySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getRegistrationStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'isAuditor' : IDL.Bool,
          'hasAdmin' : IDL.Bool,
          'isRegistered' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getSectionsByClient' : IDL.Func([IDL.Text], [IDL.Vec(Section)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [UserRecord], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAppUsers' : IDL.Func([], [IDL.Vec(AppUserPublic)], ['query']),
  'listAuditBlobs' : IDL.Func([], [IDL.Vec(AuditBlob)], ['query']),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listTemplateBlobs' : IDL.Func([], [IDL.Vec(TemplateBlob)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'loadAuditBlob' : IDL.Func([IDL.Text], [IDL.Opt(AuditBlob)], ['query']),
  'loadTemplateBlob' : IDL.Func([IDL.Text], [IDL.Opt(TemplateBlob)], ['query']),
  'saveAuditBlob' : IDL.Func([AuditBlob], [], []),
  'saveAuditorAnswers' : IDL.Func([IDL.Text, IDL.Vec(Answer)], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveManagerAnswers' : IDL.Func([IDL.Text, IDL.Vec(Answer)], [], []),
  'saveReviewerAnswers' : IDL.Func([IDL.Text, IDL.Vec(Answer)], [IDL.Text], []),
  'saveTemplateBlob' : IDL.Func([TemplateBlob], [], []),
  'seedAppAdmin' : IDL.Func([AppUser], [IDL.Bool], []),
  'sendBackReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'submitReport' : IDL.Func([IDL.Text], [SubmitResult], []),
  'submitReview' : IDL.Func([IDL.Text], [], []),
  'upsertAppUser' : IDL.Func([AppUser], [], []),
  'verifyAppUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const QuestionType = IDL.Variant({
    'radio' : IDL.Null,
    'dropdown' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'clientId' : IDL.Text,
    'questionLabel' : IDL.Text,
    'order' : IDL.Nat,
    'questionType' : QuestionType,
    'enabled' : IDL.Bool,
    'sectionId' : IDL.Text,
    'isImageMandatory' : IDL.Bool,
    'remarksEnabled' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const AppRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'auditor' : IDL.Null,
    'reviewer' : IDL.Null,
  });
  const UserRecord = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : AppRole,
    'enabled' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Section = IDL.Record({
    'id' : IDL.Text,
    'clientId' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const AppUserPublic = IDL.Record({
    'username' : IDL.Text,
    'originalRole' : AppRole,
    'elevatedUntil' : IDL.Opt(IDL.Int),
    'role' : AppRole,
    'fullName' : IDL.Text,
    'isEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ReportStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'completed' : IDL.Null,
    'reviewed' : IDL.Null,
    'draft' : IDL.Null,
    'pending_re_review' : IDL.Null,
  });
  const Answer = IDL.Record({
    'answerValue' : IDL.Text,
    'questionId' : IDL.Text,
    'imageId' : IDL.Opt(IDL.Text),
    'remarks' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'status' : ReportStatus,
    'clientId' : IDL.Text,
    'reviewerAnswers' : IDL.Vec(Answer),
    'createdAt' : IDL.Int,
    'auditorAnswers' : IDL.Vec(Answer),
    'managerComments' : IDL.Text,
    'assignedAuditor' : IDL.Principal,
    'siteName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'managerAnswers' : IDL.Vec(Answer),
  });
  const AuditBlob = IDL.Record({
    'status' : IDL.Text,
    'lastSavedAt' : IDL.Int,
    'dataJson' : IDL.Text,
    'siteId' : IDL.Text,
  });
  const Client = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const TemplateBlob = IDL.Record({
    'id' : IDL.Text,
    'createdBy' : IDL.Text,
    'updatedAt' : IDL.Int,
    'dataJson' : IDL.Text,
  });
  const AppUser = IDL.Record({
    'username' : IDL.Text,
    'originalRole' : AppRole,
    'elevatedUntil' : IDL.Opt(IDL.Int),
    'role' : AppRole,
    'fullName' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'passwordHash' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({
    'missingAnswers' : IDL.Vec(IDL.Text),
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateClient' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'addOrUpdateQuestion' : IDL.Func([Question], [IDL.Text], []),
    'addOrUpdateSection' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'addOrUpdateUser' : IDL.Func([UserRecord], [IDL.Text], []),
    'appUserHasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'approveReport' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal],
        [IDL.Text],
        [],
      ),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'deleteTemplateBlob' : IDL.Func([IDL.Text], [], []),
    'disableQuestion' : IDL.Func([IDL.Text], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getAppUserPublic' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AppUserPublic)],
        ['query'],
      ),
    'getCallerAppRole' : IDL.Func([], [AppRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestionsByClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsBySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getRegistrationStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'isAuditor' : IDL.Bool,
            'hasAdmin' : IDL.Bool,
            'isRegistered' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getSectionsByClient' : IDL.Func([IDL.Text], [IDL.Vec(Section)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [UserRecord], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAppUsers' : IDL.Func([], [IDL.Vec(AppUserPublic)], ['query']),
    'listAuditBlobs' : IDL.Func([], [IDL.Vec(AuditBlob)], ['query']),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listTemplateBlobs' : IDL.Func([], [IDL.Vec(TemplateBlob)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'loadAuditBlob' : IDL.Func([IDL.Text], [IDL.Opt(AuditBlob)], ['query']),
    'loadTemplateBlob' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TemplateBlob)],
        ['query'],
      ),
    'saveAuditBlob' : IDL.Func([AuditBlob], [], []),
    'saveAuditorAnswers' : IDL.Func(
        [IDL.Text, IDL.Vec(Answer)],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveManagerAnswers' : IDL.Func([IDL.Text, IDL.Vec(Answer)], [], []),
    'saveReviewerAnswers' : IDL.Func(
        [IDL.Text, IDL.Vec(Answer)],
        [IDL.Text],
        [],
      ),
    'saveTemplateBlob' : IDL.Func([TemplateBlob], [], []),
    'seedAppAdmin' : IDL.Func([AppUser], [IDL.Bool], []),
    'sendBackReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'submitReport' : IDL.Func([IDL.Text], [SubmitResult], []),
    'submitReview' : IDL.Func([IDL.Text], [], []),
    'upsertAppUser' : IDL.Func([AppUser], [], []),
    'verifyAppUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };