/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmitResult = {
    __kind__: "missingAnswers";
    missingAnswers: Array<string>;
} | {
    __kind__: "success";
    success: null;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: string;
    status: ReportStatus;
    clientId: string;
    reviewerAnswers: Array<Answer>;
    createdAt: bigint;
    auditorAnswers: Array<Answer>;
    managerComments: string;
    assignedAuditor: Principal;
    siteName: string;
    updatedAt: bigint;
    managerAnswers: Array<Answer>;
}
export interface UserRecord {
    principal: Principal;
    name: string;
    role: AppRole;
    enabled: boolean;
}
export interface Answer {
    answerValue: string;
    questionId: string;
    imageId?: string;
    remarks: string;
}
export interface Question {
    id: string;
    clientId: string;
    questionLabel: string;
    order: bigint;
    questionType: QuestionType;
    enabled: boolean;
    sectionId: string;
    isImageMandatory: boolean;
    remarksEnabled: boolean;
    options: Array<string>;
}
export interface Client {
    id: string;
    name: string;
    enabled: boolean;
}
export interface Section {
    id: string;
    clientId: string;
    order: bigint;
    name: string;
    enabled: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AppRole {
    manager = "manager",
    admin = "admin",
    auditor = "auditor",
    reviewer = "reviewer"
}
export enum QuestionType {
    radio = "radio",
    dropdown = "dropdown"
}
export enum ReportStatus {
    submitted = "submitted",
    completed = "completed",
    reviewed = "reviewed",
    draft = "draft",
    pending_re_review = "pending_re_review"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateClient(id: string | null, name: string, enabled: boolean): Promise<string>;
    addOrUpdateQuestion(input: Question): Promise<string>;
    addOrUpdateSection(id: string | null, name: string, order: bigint, clientId: string, enabled: boolean): Promise<string>;
    addOrUpdateUser(input: UserRecord): Promise<string>;
    approveReport(reportId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapAdmin(name: string, setupCode: string): Promise<string>;
    createReport(clientId: string, siteName: string, assignedAuditor: Principal): Promise<string>;
    deleteQuestion(id: string): Promise<void>;
    disableQuestion(id: string): Promise<void>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllSections(): Promise<Array<Section>>;
    getCallerAppRole(): Promise<AppRole>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getQuestions(): Promise<Array<Question>>;
    getQuestionsByClient(clientId: string): Promise<Array<Question>>;
    getQuestionsBySection(sectionId: string): Promise<Array<Question>>;
    getRegistrationStatus(): Promise<{
        isAuditor: boolean;
        hasAdmin: boolean;
        isRegistered: boolean;
    }>;
    getReport(reportId: string): Promise<Report | null>;
    getSectionsByClient(clientId: string): Promise<Array<Section>>;
    getUser(inputPrincipal: Principal): Promise<UserRecord>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listClients(): Promise<Array<Client>>;
    listReports(): Promise<Array<Report>>;
    listUsers(): Promise<Array<UserRecord>>;
    saveAuditorAnswers(reportId: string, answers: Array<Answer>): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveManagerAnswers(reportId: string, answers: Array<Answer>): Promise<void>;
    saveReviewerAnswers(reportId: string, answers: Array<Answer>): Promise<string>;
    sendBackReport(reportId: string, comments: string): Promise<string>;
    submitReport(reportId: string): Promise<SubmitResult>;
    submitReview(reportId: string): Promise<void>;
}
import type { Answer as _Answer, AppRole as _AppRole, Question as _Question, QuestionType as _QuestionType, Report as _Report, ReportStatus as _ReportStatus, SubmitResult as _SubmitResult, UserProfile as _UserProfile, UserRecord as _UserRecord, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateClient(arg0: string | null, arg1: string, arg2: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateClient(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateClient(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async addOrUpdateQuestion(arg0: Question): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateQuestion(to_candid_Question_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateQuestion(to_candid_Question_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateSection(arg0: string | null, arg1: string, arg2: bigint, arg3: string, arg4: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateSection(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateSection(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addOrUpdateUser(arg0: UserRecord): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateUser(to_candid_UserRecord_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateUser(to_candid_UserRecord_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReport(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapAdmin(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapAdmin(arg0, arg1);
            return result;
        }
    }
    async createReport(arg0: string, arg1: string, arg2: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteQuestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async disableQuestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableQuestion(arg0);
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSections(): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSections();
            return result;
        }
    }
    async getCallerAppRole(): Promise<AppRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAppRole();
                return from_candid_AppRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAppRole();
            return from_candid_AppRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByClient(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByClient(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByClient(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsBySection(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySection(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySection(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistrationStatus(): Promise<{
        isAuditor: boolean;
        hasAdmin: boolean;
        isRegistered: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistrationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistrationStatus();
            return result;
        }
    }
    async getReport(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSectionsByClient(arg0: string): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionsByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionsByClient(arg0);
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<UserRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_UserRecord_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_UserRecord_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients();
            return result;
        }
    }
    async listReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAuditorAnswers(arg0: string, arg1: Array<Answer>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAuditorAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAuditorAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveManagerAnswers(arg0: string, arg1: Array<Answer>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveManagerAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveManagerAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveReviewerAnswers(arg0: string, arg1: Array<Answer>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReviewerAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReviewerAnswers(arg0, to_candid_vec_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async sendBackReport(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBackReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBackReport(arg0, arg1);
            return result;
        }
    }
    async submitReport(arg0: string): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(arg0);
                return from_candid_SubmitResult_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(arg0);
            return from_candid_SubmitResult_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
}
function from_candid_Answer_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Answer): Answer {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AppRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRecord_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRecord): UserRecord {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    clientId: string;
    questionLabel: string;
    order: bigint;
    questionType: _QuestionType;
    enabled: boolean;
    sectionId: string;
    isImageMandatory: boolean;
    remarksEnabled: boolean;
    options: Array<string>;
}): {
    id: string;
    clientId: string;
    questionLabel: string;
    order: bigint;
    questionType: QuestionType;
    enabled: boolean;
    sectionId: string;
    isImageMandatory: boolean;
    remarksEnabled: boolean;
    options: Array<string>;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        questionLabel: value.questionLabel,
        order: value.order,
        questionType: from_candid_QuestionType_n22(_uploadFile, _downloadFile, value.questionType),
        enabled: value.enabled,
        sectionId: value.sectionId,
        isImageMandatory: value.isImageMandatory,
        remarksEnabled: value.remarksEnabled,
        options: value.options
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReportStatus;
    clientId: string;
    reviewerAnswers: Array<_Answer>;
    createdAt: bigint;
    auditorAnswers: Array<_Answer>;
    managerComments: string;
    assignedAuditor: Principal;
    siteName: string;
    updatedAt: bigint;
    managerAnswers: Array<_Answer>;
}): {
    id: string;
    status: ReportStatus;
    clientId: string;
    reviewerAnswers: Array<Answer>;
    createdAt: bigint;
    auditorAnswers: Array<Answer>;
    managerComments: string;
    assignedAuditor: Principal;
    siteName: string;
    updatedAt: bigint;
    managerAnswers: Array<Answer>;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n32(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        reviewerAnswers: from_candid_vec_n34(_uploadFile, _downloadFile, value.reviewerAnswers),
        createdAt: value.createdAt,
        auditorAnswers: from_candid_vec_n34(_uploadFile, _downloadFile, value.auditorAnswers),
        managerComments: value.managerComments,
        assignedAuditor: value.assignedAuditor,
        siteName: value.siteName,
        updatedAt: value.updatedAt,
        managerAnswers: from_candid_vec_n34(_uploadFile, _downloadFile, value.managerAnswers)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answerValue: string;
    questionId: string;
    imageId: [] | [string];
    remarks: string;
}): {
    answerValue: string;
    questionId: string;
    imageId?: string;
    remarks: string;
} {
    return {
        answerValue: value.answerValue,
        questionId: value.questionId,
        imageId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.imageId)),
        remarks: value.remarks
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: _AppRole;
    enabled: boolean;
}): {
    principal: Principal;
    name: string;
    role: AppRole;
    enabled: boolean;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_AppRole_n24(_uploadFile, _downloadFile, value.role),
        enabled: value.enabled
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    radio: null;
} | {
    dropdown: null;
}): QuestionType {
    return "radio" in value ? QuestionType.radio : "dropdown" in value ? QuestionType.dropdown : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    auditor: null;
} | {
    reviewer: null;
}): AppRole {
    return "manager" in value ? AppRole.manager : "admin" in value ? AppRole.admin : "auditor" in value ? AppRole.auditor : "reviewer" in value ? AppRole.reviewer : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    completed: null;
} | {
    reviewed: null;
} | {
    draft: null;
} | {
    pending_re_review: null;
}): ReportStatus {
    return "submitted" in value ? ReportStatus.submitted : "completed" in value ? ReportStatus.completed : "reviewed" in value ? ReportStatus.reviewed : "draft" in value ? ReportStatus.draft : "pending_re_review" in value ? ReportStatus.pending_re_review : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingAnswers: Array<string>;
} | {
    success: null;
}): {
    __kind__: "missingAnswers";
    missingAnswers: Array<string>;
} | {
    __kind__: "success";
    success: null;
} {
    return "missingAnswers" in value ? {
        __kind__: "missingAnswers",
        missingAnswers: value.missingAnswers
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Answer>): Array<Answer> {
    return value.map((x)=>from_candid_Answer_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRecord>): Array<UserRecord> {
    return value.map((x)=>from_candid_UserRecord_n38(_uploadFile, _downloadFile, x));
}
function to_candid_Answer_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Answer): _Answer {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_AppRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRecord): _UserRecord {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    clientId: string;
    questionLabel: string;
    order: bigint;
    questionType: QuestionType;
    enabled: boolean;
    sectionId: string;
    isImageMandatory: boolean;
    remarksEnabled: boolean;
    options: Array<string>;
}): {
    id: string;
    clientId: string;
    questionLabel: string;
    order: bigint;
    questionType: _QuestionType;
    enabled: boolean;
    sectionId: string;
    isImageMandatory: boolean;
    remarksEnabled: boolean;
    options: Array<string>;
} {
    return {
        id: value.id,
        clientId: value.clientId,
        questionLabel: value.questionLabel,
        order: value.order,
        questionType: to_candid_QuestionType_n11(_uploadFile, _downloadFile, value.questionType),
        enabled: value.enabled,
        sectionId: value.sectionId,
        isImageMandatory: value.isImageMandatory,
        remarksEnabled: value.remarksEnabled,
        options: value.options
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: AppRole;
    enabled: boolean;
}): {
    principal: Principal;
    name: string;
    role: _AppRole;
    enabled: boolean;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: to_candid_AppRole_n15(_uploadFile, _downloadFile, value.role),
        enabled: value.enabled
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answerValue: string;
    questionId: string;
    imageId?: string;
    remarks: string;
}): {
    answerValue: string;
    questionId: string;
    imageId: [] | [string];
    remarks: string;
} {
    return {
        answerValue: value.answerValue,
        questionId: value.questionId,
        imageId: value.imageId ? candid_some(value.imageId) : candid_none(),
        remarks: value.remarks
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    radio: null;
} | {
    dropdown: null;
} {
    return value == QuestionType.radio ? {
        radio: null
    } : value == QuestionType.dropdown ? {
        dropdown: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    manager: null;
} | {
    admin: null;
} | {
    auditor: null;
} | {
    reviewer: null;
} {
    return value == AppRole.manager ? {
        manager: null
    } : value == AppRole.admin ? {
        admin: null
    } : value == AppRole.auditor ? {
        auditor: null
    } : value == AppRole.reviewer ? {
        reviewer: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Answer>): Array<_Answer> {
    return value.map((x)=>to_candid_Answer_n43(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
